################################################################################################################################
#                                                                         |                                                    #
#  @Author: AchilleBourgault                                              |                                                    #
#  @Project: NostalgiaMaps                                                |  Need Plugin Development? Or something else?       #
#  @Github: https://github.com/achillebourgault                           |  ---                                               #
#  @SpigotLink: #pluginurl                                                |     Contact me on Discord: #Esporc                 #
#  *-------------------------------------------------------------------*  |                                                    #
#  Report a bug: #pluginurl                                               |                                                    #
#                                                                         |                                                    #
###### -- Configuration File -- ################################################################################################


# Owner options: none | first_player | ops | <playername>
#   The owner of the server is the only one who can manage maps and use plugin commands.
#     Note: Server Operators (ops) can always use plugin commands.
#
#   Possible values:
#   - none: Everyone are the server owners
#   - first_player: The first player that joins the server will be the server owner
#   - ops: Only servers operators are the server owners
#   - <playername>: Only the player with the specified name is the server owner. Don't use "<" and ">".
owner: none

# If you want to specify a map by default, you need to selected_map & selected_map_display_name. Otherwise, leave it as it is.
# Map name should be the name of the folder in the map's folder.
map:
  selected_map: none
  selected_map_display_name: none
  selected_map_url: none

# When a new map is added, a vote will start for the duration you define (default: 60 seconds) to decide whether to play on this map.
# You can also vote on all available maps using the '/maps vote start' command. (Could be triggered from console)
voting_system:
  start_vote_on_new_map: true
  active: true
  voting_duration: 60

# !!! WARNING !!! If you use a custom scoreboard, this may lead to incompatibilities with maps that already display scoreboards.
# Use this option only if you know what you are doing.
scoreboard:
  active: true
  title: '&e&lNostalgiaMaps'
  show_map_name: true
  show_number_of_players: true
  show_number_of_maps: true
  shift: 0
  refresh_rate: 20
