#######################################*#####################################
#                                                                           #
#   @Author: AchilleBourgault                                               #
#   @Project: NostalgiaMaps                                                 #
#   @Github: https://github.com/achillebourgault                            #
#   @SpigotLink: https://www.spigotmc.org/resources/nostalgiamaps.94887/    #
#   Report a bug: https://www.spigotmc.org/resources/nostalgiamaps.94887/   #
#                                                                           #
#######################################*#####################################

name: NostalgiaMaps
version: '${project.version}'
main: com.nostalgiamaps.NostalgiaMaps
author: AchilleBourgault
description: A plugin that allows you to download and play old Minecraft maps without having to download them yourself.
website: https://github.com/achillebourgault
api-version: 1.20
commands:
  maps:
    description: Opens the map selection GUI
    usage: /<command>
    aliases: [nostalgiamaps, nm, map]