################################################################################################################################
#                                                                         |                                                    #
#  @Author: AchilleBourgault                                              |  I'm doing this for free, but if you want to       #
#  @Project: NostalgiaMaps                                                |  support me, you can donate to me on PayPal.       #
#  @Github: https://github.com/achillebourgault                           |  ---                                               #
#  @SpigotLink: https://www.spigotmc.org/resources/nostalgiamaps.94887/   |  https://www.paypal.com/paypalme/achillebourgault  #
#  *-------------------------------------------------------------------*  |  Need Plugin Development? Or something else?       #
#  Report a bug: https://www.spigotmc.org/resources/nostalgiamaps.94887/  |     Contact me on Discord: #Esporc                 #
#                                                                         |                                                    #
###### -- Plugin Instance File -- ##############################################################################################

name: NostalgiaMaps
version: '${project.version}'
main: com.nostalgiamaps.NostalgiaMaps
author: AchilleBourgault
description: A plugin that allows you to download and play old Minecraft maps without having to download them by yourself.
website: https://github.com/achillebourgault
api-version: 1.13
commands:
  maps:
    description: Opens the map selection GUI
    usage: /<command>
    aliases: [nostalgiamaps, nm, map]